# Use a imagem base do MariaDB (última versão)
FROM mariadb:latest

# Defina variáveis de ambiente para configuração do MariaDB
ENV MARIADB_ROOT_PASSWORD=
ENV MARIADB_DATABASE=mydb

# Exponha a porta 3306
EXPOSE 3306

# Defina o volume para persistência de dados
VOLUME /var/lib/mysql
