version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db
    networks:
      - nginx-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: my-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nginx-network

volumes:
  db_data:

networks:
  nginx-network:
    external: true
