version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    image: my-spring-boot-app
    ports:
      - "8004:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - H2_DB_USER=${H2_DB_USER:-sa}
      - H2_DB_PASSWORD=${H2_DB_PASSWORD:-}
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
