spring:
  datasource:
    url: jdbc:mariadb://db:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 123
    hikari:
      connection-timeout: 30000 # 30 segundos
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
