name: Hostinger Workflow

on:
  push:
    branches:
      - main
  # workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: deploy
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: "24"
          distribution: "temurin" # ou outra distribuição de sua escolha

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Prepare files Spring Boot
        run: |
          mkdir -p SpringBoot
          cp -r target SpringBoot
          cp docker-compose.yml SpringBoot/
          cp Dockerfile.spring SpringBoot/
          cp Dockerfile.mysql SpringBoot/
          cp init.sql SpringBoot/

      - name: deletando no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          script: |
            rm -rf SpringBoot/

      - name: Copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          source: "./SpringBoot"
          target: "/root"
          overwrite: true

      - name: executing remote ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          script: |
            cd SpringBoot
            docker compose up -d --build
            docker compose restart
